// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestMessage
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestEnum int32

const (
	TestEnum_UNKOWN TestEnum = 0
	TestEnum_ENUM1  TestEnum = 1
	TestEnum_ENUM2  TestEnum = 2
)

var TestEnum_name = map[int32]string{
	0: "UNKOWN",
	1: "ENUM1",
	2: "ENUM2",
}
var TestEnum_value = map[string]int32{
	"UNKOWN": 0,
	"ENUM1":  1,
	"ENUM2":  2,
}

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}
func (x TestEnum) String() string {
	return proto.EnumName(TestEnum_name, int32(x))
}
func (x *TestEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestEnum_value, data, "TestEnum")
	if err != nil {
		return err
	}
	*x = TestEnum(value)
	return nil
}
func (TestEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TestMessage struct {
	TestEnum         *TestEnum `protobuf:"varint,1,opt,name=testEnum,enum=test.TestEnum" json:"testEnum,omitempty"`
	TestInt          *int32    `protobuf:"varint,2,req,name=testInt" json:"testInt,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessage) GetTestEnum() TestEnum {
	if m != nil && m.TestEnum != nil {
		return *m.TestEnum
	}
	return TestEnum_UNKOWN
}

func (m *TestMessage) GetTestInt() int32 {
	if m != nil && m.TestInt != nil {
		return *m.TestInt
	}
	return 0
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "test.TestMessage")
	proto.RegisterEnum("test.TestEnum", TestEnum_name, TestEnum_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x82, 0xb9, 0xb8, 0x43, 0x52,
	0x8b, 0x4b, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0xb4, 0xb8, 0x38, 0x40, 0xc2, 0xae,
	0x79, 0xa5, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x7c, 0x7a, 0x60, 0x3d, 0x21, 0x50,
	0xd1, 0x20, 0xb8, 0xbc, 0x90, 0x04, 0x17, 0x3b, 0x88, 0xed, 0x99, 0x57, 0x22, 0xc1, 0xa4, 0xc0,
	0xa4, 0xc1, 0x1a, 0x04, 0xe3, 0x6a, 0xe9, 0x70, 0x71, 0xc0, 0xd4, 0x0b, 0x71, 0x71, 0xb1, 0x85,
	0xfa, 0x79, 0xfb, 0x87, 0xfb, 0x09, 0x30, 0x08, 0x71, 0x72, 0xb1, 0xba, 0xfa, 0x85, 0xfa, 0x1a,
	0x0a, 0x30, 0xc2, 0x98, 0x46, 0x02, 0x4c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0xfd, 0x1c,
	0xa3, 0x95, 0x00, 0x00, 0x00,
}
